name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Run all checks in the development environment
        uses: docker/build-push-action@v7
        with:
          context: .
          target: checks
          pull: true
          no-cache-filters: dev,checks
          cache-from: type=gha,scope=checks
          cache-to: type=gha,scope=checks,mode=max
